% Prob2B settings
addpath 'C:\Users\lauri\OneDrive\Bureau\Internship\Prop2B\Prob2B_original'
func = @myZfunction; 
correlations =[];
arg = '';
% settings = struct('itmax',1000,'relaxf',0.25,'epsB',0.01,'epsZ',0.01,'epsH',0.2,'maxloop',10);
settings = struct('iseed',5489,'nmax',1000,'varpfail',0.1,'varpnonfail',0.5);

% Input
parameters = struct( ...
    'names', {'R'           ;'S'            ;'T'            }, ...
    'gemX',  {1.28          ;1.36           ;20             }, ...
    'sigX',  {3.55          ;0.25           ;10             }, ...
    'epsX',  {0             ;0              ;0              }, ...
    'data',  {[]            ;[]             ;[]             }, ...
    'type_v',{'GUM     '    ;'LOG     '     ;'NOR     '     }, ...  % beware: 8 character string
    'x',     {0             ;0              ;0              }, ...
    'u',     {0             ;0              ;0              }, ...
    'rhot',  {0             ;0              ;0              }, ...
    'alfa',  {0             ;0              ;0              });

% the run        
%[results, parametersOut] = FormDump(func, parameters, correlations, settings, arg);

%disp(results)
[results parametersOut] = CrMc(func, parameters, correlations, settings, arg);