---
title: "Untitled"
format: html
editor: visual
---

```{r}
Cabauw_KNW <- read.csv("../../../Data/Data_KNW/modeldata.csv")
Cabauw_KNW$DateTime = ymd_hms(Cabauw_KNW$DateTime)
Cabauw_KNW$Year = year(Cabauw_KNW$Year)
Cabauw_KNW = Cabauw_KNW[Cabauw_KNW$Year > min(Cabauw_KNW$Year) & Cabauw_KNW$Year < max(Cabauw_KNW$Year),]

Cabauw_measure <- read.csv("../../../Data/Data_Cabauw/Cabauw_measure.csv")
Cabauw_measure$Year = year(Cabauw_measure$Year)
Cabauw_measure$DateTime = ymd_hms(Cabauw_measure$DateTime)
Cabauw_measure = Cabauw_measure[Cabauw_measure$Year > 2000 & Cabauw_measure$Year < 2020,]


Cabauw_RACMO <- read.csv("../../../Data/Data_RACMO/fulldata.csv")
Cabauw_RACMO$DateTime = ymd_hms(Cabauw_RACMO$DateTime)
Cabauw_RACMO = Cabauw_RACMO[Cabauw_RACMO$Year > min(Cabauw_RACMO$Year) & Cabauw_RACMO$Year < max(Cabauw_RACMO$Year),]





all_data = list(measure = Cabauw_measure,KNW = Cabauw_KNW, RACMO = Cabauw_RACMO)

all_data$RACMOh6 <- Cabauw_RACMO %>%
  mutate(
    DT = DateTime
  )%>%
  group_by(DateTime = date(DT) + hours(floor(hour(DT)/6)*6)) %>%
  summarise(
    Year = as.integer(mean(Year)),
    w10m = mean(w10m),
    F050 = mean(fh050),
    F100 = mean(fh100),
    F150 = mean(fh150),
    F200 = mean(fh200),
    F250 = mean(fh250),
    F300 = mean(fh300),
    # w10max = max(w10max)
  )

all_data$RACMOh12 <- Cabauw_RACMO %>%
  mutate(
    DT = DateTime
  )%>%
  group_by(DateTime = date(DT) + hours(floor(hour(DT)/12)*12)) %>%
  summarise(
    Year = as.integer(mean(Year)),
    w10m = mean(w10m),
    F050 = mean(fh050),
    F100 = mean(fh100),
    F150 = mean(fh150),
    F200 = mean(fh200),
    F250 = mean(fh250),
    F300 = mean(fh300),
    # w10max = max(w10max)
  )


all_data$RACMOh24 <- Cabauw_RACMO %>%
  mutate(
    DT = DateTime
  )%>%
  group_by(DateTime = date(DT)) %>%
  summarise(
    Year = as.integer(mean(Year)),
    w10m = mean(w10m),
    F050 = mean(fh050),
    F100 = mean(fh100),
    F150 = mean(fh150),
    F200 = mean(fh200),
    F250 = mean(fh250),
    F300 = mean(fh300),
    # w10max = max(w10max)
  )

```

```{r}
racmo = tailindexplot_col(Cabauw_RACMO,4,columns = c("w10m","fh050","fh100","fh150","fh200","fh250","fh300"), th=0.1, winter=T, parameter='tail', method = "GW")$df

racmo6 = tailindexplot_col(all_data$RACMOh6,2,columns = c("w10m",'F050','F100','F150','F200','F250','F300'), th=0.1, winter=T, parameter='tail', method = "GW")$df

racmo12 = tailindexplot_col(all_data$RACMOh12,1,columns = c("w10m",'F050','F100','F150','F200','F250','F300'), th=0.1, winter=T, parameter='tail', method = "GW")$df

racmo24 = tailindexplot_col(all_data$RACMOh24,1,columns = c("w10m",'F050','F100','F150','F200','F250','F300'), th=0.1, winter=T, parameter='tail', method = "GW")$df


measure = tailindexplot_col(Cabauw_measure,12*6,columns = c("F010","F020","F040","F080","F140","F200"),th=0.1,parameter = 'tail',winter = T,method = "GW")$df

knw = tailindexplot_col(Cabauw_KNW,12,columns = c("F010","F020","F040","F060","F080","F100","F150","F200"),th=0.1,parameter = 'tail',winter = T,method = "GW")$df

wgmax = rbind(tailindexplot_col(Cabauw_measure,timesep = 12*6,method = 'GW',columns = c("PF010","PF020","PF040","PF080","PF140","PF200"),th = 0.1,parameter = 'tail',winter = T)$df,
               tailindexplot_col(Cabauw_RACMO,timesep = 4,method = 'GW',columns = c("wgmax"),th = 0.1,parameter = 'tail',winter = T)$df)
wgmax$dataset <- c(rep('Observations',6),'RACMO')
wgmax$time <- 3/3600

racmo$time <- 3
racmo$dataset <- "RACMO"
racmo6$time <- 6
racmo6$dataset <- "RACMO"
racmo12$time <- 12
racmo12$dataset <- "RACMO"
racmo24$time <- 24
racmo24$dataset <- "RACMO"
measure$time <- 1/6
measure$dataset <- "Observations"
knw$time <- 1
knw$dataset <- "KNW"

df = rbind(measure,knw,racmo,racmo6,racmo12,racmo24,wgmax)
df$height = as.numeric(gsub(".*?(\\d+).*", "\\1", df$group))
df$height[df$height==0] = 10

fit <- lm(val ~ log10(time), data = df %>% filter(height==10))

# Create new data for extrapolation
new_data <- data.frame(time = df$time)  # Extrapolate to x = 0.01 for log scale

# Predict using the model
new_data$val <- predict(fit, newdata = new_data)
for (h in unique(df$height)){
gg= ggplot(df %>% filter(height%in%c(10,200)),aes(x=time,y=val,color=factor(height)))+
  geom_pointrange(aes(ymin=lb,ymax=ub,lty=dataset,pch=dataset),position = position_dodge2(0.2))+
  # geom_smooth(method = 'lm')+
  labs(title = paste("tail index estimated on all datasets at 10m and 200m, th=0.1, GW"))+
  ylab("tail index")+
  xlab("Averaging/Sampling time (h)")+
  scale_x_log10()
print(gg)
}
```
