% create structure for stochastic parameters --> R_D-1/2*rho*V1^2*cr^2*Cmax1*A_ref*X
run("initialize_stochastic_properties")

parameters = struct( ...
'names', {'theta'               ;'rho_steel'    ; 'fy'      ; 'fc'     ; 't'        ;'V'       ;'C'      ;'cr_squared'      ;'X'        ;'Sv'       ;'cd'       }, ...
'gemX',  {mean_theta_M          ; 1.0/100       ;  mean_fy  ; mean_fc  ; 0.5        ;NaN       ;NaN      ;NaN               ;1          ;1          ;1.0    }, ...
'sigX',  {V_theta_M*mean_theta_M; 0.01/100      ;  std_fy   ; std_fc   ; 0.01       ;NaN       ;NaN      ;NaN               ;0.1        ;NaN        ;0.15     }, ...
'epsX',  {0                     ; 0             ; 0         ; 0         ;0          ;0         ;0        ;0                 ;0          ;0          ;0       }, ...
'data',  {[]                    ;[]             ;[]         ;[]         ;[]         ;[]        ;[]       ;[]                ;[]         ;[]         ;[]      }, ...
'type_v',{'LOG     '            ;'DET     '     ;'LOG     ' ;'LOG     ' ;'DET     ' ;'TAB     ';'TAB     ';'LOG     '       ;'NOR     ' ;'DET     ' ;'NOR     '   }, ...  % beware: 8 character string
'x',     {mean_theta_M          ;1.0/100        ; mean_fy   ; mean_fc   ;0.5        ;NaN       ;NaN      ;1                 ;1          ;1          ;1      }, ...
'u',     {0                     ;0              ;0          ;0          ;0          ;0         ;0        ;0                 ;0          ;0          ;0      }, ...
'rhot',  {0                     ;0              ;0          ;0          ;0          ;0         ;0        ;0                 ;0          ;0          ;0      }, ...
'alfa',  {0                     ;0              ;0          ;0          ;0          ;0         ;0        ;0                 ;0          ;0          ;0      });