function z = myZfunctionQ2(x)
% R_D(1)+1/2*rho*V1(2)^2*Cmax1(3)*cr(4)^2*A_ref*X(5)
% % create structure for stochastic parameters --> R_D-1/2*rho*V1^2*cr^2*Cmax1*A_ref*X
% parameters = struct( ...
% 'names', {'theta'               ;'rho_steel'; 'fy'      ; 'fc'     ; 't'    ;'V'       ;'C'      ;'cr_squared'      ;'X'        ;'Sv'       ;'cd'       }, ...
% 'gemX',  {mean_theta_M          ; 1.0       ;  mean_fy  ; mean_fc  ; 0.5    ;20.7      ;0        ;1.1               ;1          ;1          ;1    }, ...
% 'sigX',  {V_theta_M*mean_theta_M;  0.01     ;  std_fy   ; std_fc   ; 0.01   ;3.0       ;0        ;0.1               ;0.1        ;0.1        ;0.15     }, ...
% 'epsX',  {0                     ; 0         ; 0         ; 0         ;0      ;0         ;0        ;0                 ;0          ;0          ;0       }, ...
% 'data',  {[]                    ;[]         ;[]         ;[]         ;[]     ;[]        ;[]       ;[]                ;[]         ;[]         ;[]      }, ...
% 'type_v',{'LOG'                 ;'DET'      ;'LOG'      ;'LOG'      ;'DET'  ;'TAB     ';'TAB     ';'LOG     '       ;'NOR     ' ;'DET     ' ;'DET     '   }, ...  % beware: 8 character string
% 'x',     {mean_theta_M          ;1.0        ; mean_fy   ; mean_fc   ;0.5    ;0         ;1.1      ;1                 ;1          ;1          ;1      }, ...
% 'u',     {0                     ;0          ;0          ;0          ;0      ;0         ;0        ;0                 ;0          ;0          ;0      }, ...
% 'rhot',  {0                     ;0          ;0          ;0          ;0      ;0         ;0        ;0                 ;0          ;0          ;0      }, ...
% 'alfa',  {0                     ;0          ;0          ;0          ;0      ;0         ;0        ;0                 ;0          ;0          ;0      });

run('Deterministic_values')

z = x(1)*Asw_s*(b_core-0.39*((x(2)*(b_core^2-(b_core-2*x(5))^2)*x(3))/(0.75*x(4)*b_core)))*2.5*x(3)-0.5*rho*x(6)^2*x(7)*x(8)*A_ref*x(9)*x(10)^2*x(11);